### ISSUE TITLE
Filter for HARD state only

### ISSUE THREAD

**Issue by tkuther** [alerta/nagios-alerta#13]
Is there a way to filter out SOFT state checks, so only HARD states are shown in Alerta?

If not yet, this would be a great feature.

**Comment by satterly** [comment]
Not currently. Can you explain why you might only want to see HARD state changes and ignore SOFT ones?

**Comment by tkuther** [comment]
Mainly to get a consistent alerting behaviour. Nagios (or Centreon in our case) sends out an email alert for hard states only, and only those alerts should show up in the centralized alert dashboard, too. It takes into account what you configured in the service check regarding max retries and retry check interval before an alert is fired.

Having a simple boolean config option like `hard_states_only=true` could achieve this. A default value of _false_ would ensure no change to current behaviour.

**Comment by satterly** [comment]
Fixed in version 3.3.3

**Comment by satterly** [comment]
Note: Usage is `hard_only=1` to enable.

**Comment by tkuther** [comment]
Perfect. Thank you!
