### ISSUE TITLE
http user-agent value. possible to define?

### ISSUE THREAD

**Issue by oyermolenko** [alerta/nagios-alerta#22]
Hi, 

How to define default user-agent value? I would tell it empty according to my http logs.
Now I'm trying to organize backend management in varnish (I mean route http requests)
nagios -> haproxy -> varnish -> alerta

Thanks a lot for your help.

Oleksandr

**Comment by satterly** [comment]
Hi, The User Agent is not currently set by the nagios alerta NEB. Would you want it to be set to a fixed value (eg. `Nagios-to-Alerta Gateway/3.5.0` ) or do you want to be able to set it to something yourself?

For future reference: https://curl.haxx.se/libcurl/c/CURLOPT_USERAGENT.html

**Comment by oyermolenko** [comment]
Hi, Nick, enough for me have fixed well known ID
