### ISSUE TITLE
Question - Icinga2 Support

### ISSUE THREAD

**Issue by iDemonix** [alerta/nagios-alerta#30]
Hi,

Unfortunately Icinga2 dropped neb support for 2.x. I'm running around 5-6 Icinga2 boxes and need to pipe alerts to Alerta like I'm doing with Prometheus.

When an Icinga2 notification fires, it triggers a Python script which does some magic and sends info off to our ticketing system. Would it be possible to do the same with Icinga2, possibly to a webhook? I notice there's no generic webhook, though, so I'm not sure if that's possible? Or am I going to have to install the alerta CLI on each machine and interact that way?

**Comment by satterly** [comment]
The "generic webhook" is to simply use the `POST /alert` endpoint described [here](https://docs.alerta.io/en/latest/api/reference.html#create-an-alert). If you want to do some pre-processing of the alert before it's ingested by Alerta you can write a plugin.

Alternatively, create a "custom webhook" using one of the example [here](https://github.com/alerta/alerta-contrib/tree/master/webhooks) as a starting point.

**Comment by iDemonix** [comment]
Thanks, I didn't realise that was possible :) I will look in to it.
