### ISSUE TITLE
Can't send alert from Nagios to Alerta

### ISSUE THREAD

**Issue by marcodesantis71** [alerta/nagios-alerta#35]
Hi All,

I have installed Alerta and Nagios on different servers.

On the first server (Alerta) I follow the steps on official documentation on Ubuntu 16 (http://docs.alerta.io/en/latest/tutorials.html#tutorials). It run and I can send alarm from command line on localhost.

On second server I've installed Nagios Core 4 and Nagios-alerta from this repo. 
But I can't send any alarm. 
I try some configuration but I receive different error:

1) broker_module=/usr/lib/nagios/alerta-neb.o http://10.211.55.10:80/api key=API_KEY --> [1544546431] alerta: HTTP server error (status=500)
2) broker_module=/usr/lib/nagios/alerta-neb.o http://10.211.55.10:8080 key=API_KEY -->alerta: curl_easy_perform() failed: Couldn't connect to server (on Alerta server any service on 8080 port)
3)  broker_module=/usr/lib/nagios/alerta-neb.o http://10.211.55.10 key=API_KEY --> 
[1544546544] alerta: HTTP server error (status=404)

where I wrong?

Thx.

**Comment by satterly** [comment]
If you set `debug=1` you will be able to see the HTTP request and response in the logs. Without that it's hard to know what's going on.

**Example**
```
broker_module=/usr/lib/nagios/alerta-neb.o http://localhost:8080 debug=1
```

**Comment by marcodesantis71** [comment]
Hi,


thanks. With debug mode I saw the error. So I solved it.
