### ISSUE TITLE
ALERTA WEBUI - NAGIOS = How to acknowledge alert in NAGIOS via Alerta

### ISSUE THREAD

**Issue by garnesh82** [alerta/nagios-alerta#39]
Is there a way to send acknowledgement from Alerta-WebUI to NAGIOS core?

**Comment by satterly** [comment]
If nagios can receive an acknowledgement via a URL or some other way over the network or via a script/command then yes, it's possible. Write a plugin to trigger the action you need when you ack an alert in Alerta.
