### ISSUE TITLE
all event in /var/log/messages

### ISSUE THREAD

**Issue by jbeaujour** [alerta/nagios-alerta#45]
Hello
Issue Summary
When Alerta Neb is running, it log all event (curl response ?) in /var/log/messages even if notin debug mode
/var/log/messages before : 10Mo after 700Mo !!

Environment

    OS: Linux
    Nagios Alerta version: [5.0.1]

To Reproduce

    stop/start nagios
    look on /var/log/messages
    See messages

Expected behavior
No messages in /var/log/messages but in /var/log/alerta/alerta.log with verbosity level

Screenshots for one event
Jul 26 15:20:40 nagios: {
Jul 26 15:20:40 nagios: "alert": {
Jul 26 15:20:40 nagios: "attributes": {
Jul 26 15:20:40 nagios: "CI source": "xxxxxxxxxxxxxxxxxxxxxx.fr",
Jul 26 15:20:40 nagios: "Fiche_Consigne": "<a href=hxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx target=\"_blank\">Nagios.pdf</a>",
Jul 26 15:20:40 nagios: "Sonde_Nagios": "check_specifique_UMANIS_JOBQ_Ctrl_Alert_Lost",
Jul 26 15:20:40 nagios: "checkCommand": "check_specifique_UMANIS_JOBQ_Ctrl_Alert_Lost",
Jul 26 15:20:40 nagios: "commandLine": "/opt/nrpe/libexec/check_ACT400_liste.pl \"ZZ2023CD\" xxxxxxxxxxxxxxxxxxxxxxxxxx \"OPT0001\" \"OPT0002\""
Jul 26 15:20:40 nagios: },
Jul 26 15:20:40 nagios: "correlate": [],
Jul 26 15:20:40 nagios: "createTime": "2021-07-20T09:05:13.536Z",
Jul 26 15:20:40 nagios: "customer": "xxxxxxxxxxxxxxx",
Jul 26 15:20:40 nagios: "duplicateCount": 5,
Jul 26 15:20:40 nagios: "environment": "recette",
Jul 26 15:20:40 nagios: "event": "job-ctrl-alert-lost .job-ctrl-alert-lost",
Jul 26 15:20:40 nagios: "group": "Nagios",
Jul 26 15:20:40 nagios: "history": [
Jul 26 15:20:40 nagios: {
Jul 26 15:20:40 nagios: "event": "job-ctrl-alert-lost .job-ctrl-alert-lost",
Jul 26 15:20:40 nagios: "href": "/api/alert/883ab417-b890-49e7-a9bb-6bd9eb24606a",
Jul 26 15:20:40 nagios: "id": "883ab417-b890-49e7-a9bb-6bd9eb24606a",
Jul 26 15:20:40 nagios: "severity": "normal",
Jul 26 15:20:40 nagios: "status": "closed",
Jul 26 15:20:40 nagios: "text": "OK : OPT0001 - Aucune alerte non transmise \u00e0 OMi",
Jul 26 15:20:40 nagios: "timeout": 86400,
Jul 26 15:20:40 nagios: "type": "new",
Jul 26 15:20:40 nagios: "updateTime": "2021-07-20T09:05:13.536Z",
Jul 26 15:20:40 nagios: "user": "adm-randreet",
Jul 26 15:20:40 nagios: "value": "1/2 (Hard)"
Jul 26 15:20:40 nagios: }
Jul 26 15:20:40 nagios: ],
Jul 26 15:20:40 nagios: "href": "/api/alert/883ab417-b890-49e7-a9bb-6bd9eb24606a",
Jul 26 15:20:40 nagios: "id": "883ab417-b890-49e7-a9bb-6bd9eb24606a",
Jul 26 15:20:40 nagios: "lastReceiveId": "ddffe313-c72a-4eb9-ac01-a1f1798c7f59",
Jul 26 15:20:40 nagios: "lastReceiveTime": "2021-07-26T13:20:40.403Z",
Jul 26 15:20:40 nagios: "origin": "nagios/xxxxxxxxxxxxxx",
Jul 26 15:20:40 nagios: "previousSeverity": "indeterminate",
Jul 26 15:20:40 nagios: "rawData": "",
Jul 26 15:20:40 nagios: "receiveTime": "2021-07-20T09:05:13.546Z",
Jul 26 15:20:40 nagios: "repeat": true,
Jul 26 15:20:40 nagios: "resource": "xxxxxxxxxxxxxxxxxxxxxxx",
Jul 26 15:20:40 nagios: "service": [
Jul 26 15:20:40 nagios: "NAGIOS"
Jul 26 15:20:40 nagios: ],
Jul 26 15:20:40 nagios: "severity": "normal",
Jul 26 15:20:40 nagios: "status": "closed",
Jul 26 15:20:40 nagios: "tags": [
Jul 26 15:20:40 nagios: "Active"
Jul 26 15:20:40 nagios: ],
Jul 26 15:20:40 nagios: "text": "OK : OPT0001 - Aucune alerte non transmise \u00e0 OMi",
Jul 26 15:20:40 nagios: "timeout": 86400,
Jul 26 15:20:40 nagios: "trendIndication": "noChange",
Jul 26 15:20:40 nagios: "type": "nagiosServiceAlert",
Jul 26 15:20:40 nagios: "updateTime": "2021-07-20T09:05:13.546Z",
Jul 26 15:20:40 nagios: "value": "1/2 (Hard)"
Jul 26 15:20:40 nagios: },
Jul 26 15:20:40 nagios: "id": "883ab417-b890-49e7-a9bb-6bd9eb24606a",
Jul 26 15:20:40 nagios: "status": "ok"
Jul 26 15:20:40 nagios: }
                
Additional context
Uses with mod_gearman and livestatus (1.2.8)

Thank's

**Comment by satterly** [comment]
It should only log curl requests/responses in debug mode...

https://github.com/alerta/nagios-alerta/blob/40bc6edb303e1d29ea5d43d5438cb9d99139bb5e/src/alerta-neb.c#L219-L224

If you can show in your `nagios.cfg` configuration file where you call `broker_module ` I'll reopen this issue and see if I can reproduce the problem.
